-- Auto-generated by scripts/geocode-missing.js
-- Apply: npx wrangler d1 execute patriot_directory_db --remote --file=data/geocode-missing.sql

UPDATE businesses SET latitude = 44.5990718, longitude = -72.5002608 WHERE slug = 'humming-meadow-honey';
UPDATE businesses SET latitude = 41.4899827, longitude = -71.3137707 WHERE slug = 'kiel-james-patrick';
UPDATE businesses SET latitude = 31.2638905, longitude = -98.5456116 WHERE slug = 'the-buffalo-wool-co';
UPDATE businesses SET latitude = 43.6447642, longitude = -114.015407 WHERE slug = 'the-woolshire';
UPDATE businesses SET latitude = 43.6211955, longitude = -84.6824346 WHERE slug = 'fox-and-root';
UPDATE businesses SET latitude = 43.1561681, longitude = -75.8449946 WHERE slug = 'ambrosian-candle-co';
UPDATE businesses SET latitude = 37.1232245, longitude = -78.4927721 WHERE slug = 'tamburn-bindery';
UPDATE businesses SET latitude = 41.6018004, longitude = -93.6466594 WHERE slug = 'middleborne-arms';
UPDATE businesses SET latitude = 37.5385087, longitude = -77.43428 WHERE slug = 'black-wolf-homestead';
UPDATE businesses SET latitude = 32.3293809, longitude = -83.1137366 WHERE slug = 'baritus-catholic-illustration';
UPDATE businesses SET latitude = 43.1387986, longitude = -72.5073793 WHERE slug = 'orthodox-mason';
UPDATE businesses SET latitude = 34.6067588, longitude = -87.0883459 WHERE slug = 'seraphim-print-studio';
UPDATE businesses SET latitude = 47.6038321, longitude = -122.330062 WHERE slug = 'gubba-homestead';
UPDATE businesses SET latitude = 40.9699889, longitude = -77.7278831 WHERE slug = 'wading-smith-woodworks';
UPDATE businesses SET latitude = 38.7478401, longitude = -85.0671725 WHERE slug = 'cottage-pastures';
UPDATE businesses SET latitude = 32.9481789, longitude = -96.7297206 WHERE slug = 'wasson-watch-co';
UPDATE businesses SET latitude = 35.7730076, longitude = -86.2820081 WHERE slug = 'peaces-of-indigo';
UPDATE businesses SET latitude = 35.1460249, longitude = -90.0517638 WHERE slug = 'nicholas-hayford-jewelry';
UPDATE businesses SET latitude = 40.9699889, longitude = -77.7278831 WHERE slug = 'eli-sherbondy-machining';
UPDATE businesses SET latitude = 41.9216734, longitude = -93.3122705 WHERE slug = 'primal-aromas';
UPDATE businesses SET latitude = 28.709211, longitude = -100.4992936 WHERE slug = 'evers-forge-works';
UPDATE businesses SET latitude = 44.4308975, longitude = -89.6884637 WHERE slug = 'silver-gold-honey-company';
UPDATE businesses SET latitude = 41.3604966, longitude = -93.5613292 WHERE slug = 'armadillo-acres-farm';
UPDATE businesses SET latitude = 33.907879, longitude = -97.2889056 WHERE slug = 'tlc-ranch';
UPDATE businesses SET latitude = 30.2711286, longitude = -97.7436995 WHERE slug = 'puresteel-co';
UPDATE businesses SET latitude = 47.2150945, longitude = -123.100706 WHERE slug = 'taylor-shellfish-farms';
UPDATE businesses SET latitude = 33.6874388, longitude = -80.4363743 WHERE slug = 'appalachian-wood-homestead';
UPDATE businesses SET latitude = 44.3379214, longitude = -72.7563801 WHERE slug = 'parros-gun-shop';
UPDATE businesses SET latitude = 34.6628067, longitude = -80.700546 WHERE slug = 'benford-brewing';
UPDATE businesses SET latitude = 31.7606732, longitude = -93.0860209 WHERE slug = 'louisiana-crawfish-company';
UPDATE businesses SET latitude = 39.8842304, longitude = -82.7535049 WHERE slug = 'she-must-be-loved';