-- Auto-generated by scripts/scrape-og-images.js
-- Run: npx wrangler d1 execute patriot_directory_db --remote --file=data/photos-update.sql

UPDATE businesses SET photo_url = 'https://k8u8y6t8.rocketcdn.me/wp-content/uploads/2017/08/cropped-Gift-Box-4.jpg' WHERE slug = 'jimmys-famous-seafood';
UPDATE businesses SET photo_url = 'http://exumbrisdesigns.com/cdn/shop/files/D98B766E-95DC-4CD1-AD05-BC26E0E901DE_1200x1200.jpg?v=1612934348' WHERE slug = 'ex-umbris-designs';
UPDATE businesses SET photo_url = 'http://toorknives.com/cdn/shop/files/Toor_Knives_Social_Image_1200x1200.png?v=1694192644' WHERE slug = 'toor-knives';
UPDATE businesses SET photo_url = 'http://www.chagrinvalleysoapandsalve.com/cdn/shop/files/chagrinvalleylogo221.png?v=1678936627' WHERE slug = 'chagrin-valley-soap-salve';
UPDATE businesses SET photo_url = 'https://images.discerningassets.com/image/upload/v1699041699/q5uxype86vquwajexzy8.jpg' WHERE slug = 'debra-bruner-studio';
UPDATE businesses SET photo_url = 'http://enakflavors.com/cdn/shop/files/IMG_2650.jpg?v=1740051496' WHERE slug = 'enak-flavors';
UPDATE businesses SET photo_url = 'https://static.wixstatic.com/media/a54f71_22e4dfa4fc694ab8a87f63b4542a1e9c~mv2.png/v1/fill/w_2500,h_1406,al_c/a54f71_22e4dfa4fc694ab8a87f63b4542a1e9c~mv2.png' WHERE slug = 'infiniti-crafting-company';
UPDATE businesses SET photo_url = 'http://thedoghouse.coffee/cdn/shop/files/The_Dog_House_COFFEE_8c7a4004-9fb6-428c-85a9-4076dc23c1d8.png?v=1669836049' WHERE slug = 'the-doghouse-coffee';
UPDATE businesses SET photo_url = 'https://cdn.shopify.com/s/files/1/0015/5667/6685/files/OAM_Logo_Horizontal_Outline_720x_54a9948f-fd20-4562-ac1b-26547e00ed66.png?height=628&pad_color=fff&v=1770161815&width=1200' WHERE slug = 'original-appearance-manufacturing';
UPDATE businesses SET photo_url = 'https://littleseedfarm.com/cdn/shop/files/251218_lsf-bali_57.png?v=1769527226&width=1200' WHERE slug = 'little-seed-farm';