-- Auto-generated by scripts/scrape-og-images.js
-- Run: npx wrangler d1 execute patriot_directory_db --remote --file=data/photos-update.sql

UPDATE businesses SET photo_url = 'https://k8u8y6t8.rocketcdn.me/wp-content/uploads/2017/08/cropped-Gift-Box-4.jpg' WHERE slug = 'jimmys-famous-seafood';
UPDATE businesses SET photo_url = 'http://exumbrisdesigns.com/cdn/shop/files/D98B766E-95DC-4CD1-AD05-BC26E0E901DE_1200x1200.jpg?v=1612934348' WHERE slug = 'ex-umbris-designs';
UPDATE businesses SET photo_url = 'http://toorknives.com/cdn/shop/files/Toor_Knives_Social_Image_1200x1200.png?v=1694192644' WHERE slug = 'toor-knives';
UPDATE businesses SET photo_url = 'http://www.chagrinvalleysoapandsalve.com/cdn/shop/files/chagrinvalleylogo221.png?v=1678936627' WHERE slug = 'chagrin-valley-soap-salve';
UPDATE businesses SET photo_url = 'https://images.discerningassets.com/image/upload/v1699041699/q5uxype86vquwajexzy8.jpg' WHERE slug = 'debra-bruner-studio';
UPDATE businesses SET photo_url = 'http://enakflavors.com/cdn/shop/files/IMG_2650.jpg?v=1740051496' WHERE slug = 'enak-flavors';
UPDATE businesses SET photo_url = 'https://static.wixstatic.com/media/a54f71_22e4dfa4fc694ab8a87f63b4542a1e9c~mv2.png/v1/fill/w_2500,h_1406,al_c/a54f71_22e4dfa4fc694ab8a87f63b4542a1e9c~mv2.png' WHERE slug = 'infiniti-crafting-company';
UPDATE businesses SET photo_url = 'http://thedoghouse.coffee/cdn/shop/files/The_Dog_House_COFFEE_8c7a4004-9fb6-428c-85a9-4076dc23c1d8.png?v=1669836049' WHERE slug = 'the-doghouse-coffee';
UPDATE businesses SET photo_url = 'https://cdn.shopify.com/s/files/1/0015/5667/6685/files/OAM_Logo_Horizontal_Outline_720x_54a9948f-fd20-4562-ac1b-26547e00ed66.png?height=628&pad_color=fff&v=1770161815&width=1200' WHERE slug = 'original-appearance-manufacturing';
UPDATE businesses SET photo_url = 'http://www.hummingmeadow.com/cdn/shop/files/Logo_Humming_Meadow_Honey_Dark_Forest_Banner_Style_copy_1ef9514e-f9bd-4e15-bcf1-414ddb56578d.jpg?v=1771114414' WHERE slug = 'humming-meadow-honey';
UPDATE businesses SET photo_url = 'https://thewoolshire.com/cdn/shop/files/The-Woolshire-Northwest-Wool-_Logo_Final_PNG_1204x630.png?v=1668316288' WHERE slug = 'the-woolshire';
UPDATE businesses SET photo_url = 'https://static.wixstatic.com/media/846bed_adc7ec44701c442687b0f5561fa2cbe8~mv2.png/v1/fill/w_2500,h_1480,al_c/846bed_adc7ec44701c442687b0f5561fa2cbe8~mv2.png' WHERE slug = 'fox-and-root';
UPDATE businesses SET photo_url = 'http://ambrosiancandles.com/cdn/shop/files/IMG_2808_9dbad381-efcb-4b29-b2bc-b47024332028_1200x1200.png?v=1728060849' WHERE slug = 'ambrosian-candle-co';
UPDATE businesses SET photo_url = 'http://cotedge.com/cdn/shop/files/SEO_Card_2.png?v=1752104598' WHERE slug = 'cotedge-socks';
UPDATE businesses SET photo_url = 'https://static.wixstatic.com/media/51f14a_0e5f37e122374edcaea512ce28568c0f%7Emv2.jpeg/v1/fit/w_2500,h_1330,al_c/51f14a_0e5f37e122374edcaea512ce28568c0f%7Emv2.jpeg' WHERE slug = 'middleborne-arms';
UPDATE businesses SET photo_url = 'https://static.wixstatic.com/media/756499_d2d4d988afe44d4498a4d4e61ec0528a~mv2.png/v1/fill/w_2500,h_2498,al_c/756499_d2d4d988afe44d4498a4d4e61ec0528a~mv2.png' WHERE slug = 'baritus-catholic-illustration';
UPDATE businesses SET photo_url = 'http://static1.squarespace.com/static/574a456bc2ea517f706337be/t/594d863903596eed98f56530/1498252860958/unnamed.png?format=1500w' WHERE slug = 'orthodox-mason';
UPDATE businesses SET photo_url = 'https://i.etsystatic.com/isa/44d665/1138321534530/isa_fullxfull.1138321534530_e0x9.jpg?version=0' WHERE slug = 'seraphim-print-studio';
UPDATE businesses SET photo_url = 'http://shop.gubbahomestead.com/cdn/shop/files/gubba_homestead_arvoti_1200x628.png?v=1721067681' WHERE slug = 'gubba-homestead';
UPDATE businesses SET photo_url = 'https://i0.wp.com/cottagepastures.com/wp-content/uploads/2024/12/CP-35-scaled.jpg' WHERE slug = 'cottage-pastures';
UPDATE businesses SET photo_url = 'http://wassonwatch.com/cdn/shop/files/homepage_66cf5930-2e44-4bee-bab3-0787248fb4c1.jpg?v=1652721308' WHERE slug = 'wasson-watch-co';
UPDATE businesses SET photo_url = 'https://assets.bigcartel.com/account_images/5937664/322E2726-DD5D-4753-AFC4-B70B48BAE443.jpeg?auto=format&amp;fit=max&amp;h=1200&amp;w=1200' WHERE slug = 'peaces-of-indigo';
UPDATE businesses SET photo_url = 'http://www.primalaromas.com/cdn/shop/files/Primal_Aromas_e42a86e6-2f3a-42fa-babf-2bee01fbaf9b.png?v=1731855794' WHERE slug = 'primal-aromas';
UPDATE businesses SET photo_url = 'http://static1.squarespace.com/static/5704cd33ab48de4f155128f4/t/64d9714fe20ca175648573ba/1691971919290/116kaz.jpg?format=1500w' WHERE slug = 'evers-forge-works';
UPDATE businesses SET photo_url = 'http://halfacre-farms.com/cdn/shop/files/2017-03-04_16.33.00.jpg?v=1655592127' WHERE slug = 'armadillo-acres-farm';
UPDATE businesses SET photo_url = 'http://tlcranch.com/cdn/shop/files/Screenshot_2024-10-24_at_12.08.54_PM.png?v=1729789753' WHERE slug = 'tlc-ranch';
UPDATE businesses SET photo_url = 'https://cdn.shopify.com/s/files/1/0795/8528/0215/files/product_page_4039afa3-2f98-42c9-b3b0-b246849009ae.jpg?v=1770643127' WHERE slug = 'puresteel-co';
UPDATE businesses SET photo_url = 'http://americanlictor.com/cdn/shop/files/IMG_2274_b96adf01-8c28-4767-884e-d7b912f3d3fe.jpg?v=1742081154' WHERE slug = 'american-lictor';
UPDATE businesses SET photo_url = 'http://bowtiewoodworks.com/cdn/shop/files/Bowtie_Logo_Filled.jpg?v=1681228511' WHERE slug = 'bowtied-woodwork';
UPDATE businesses SET photo_url = 'https://m.media-amazon.com/images/I/81Yt7PSUYeL._CLa|1408,1248|613botgsBrL.jpg,81nMuIQ1eCL.jpg|0,0,640,1248+768,0,640,1248+320,0,768,1248_._SY300_.jpg' WHERE slug = 'felgenland-saga';
UPDATE businesses SET photo_url = 'https://img1.wsimg.com/isteam/ip/7c20c964-63d4-4e17-8333-9c7f98ddfeeb/IMG_5784.jpeg' WHERE slug = 'benford-brewing';
UPDATE businesses SET photo_url = 'http://static1.squarespace.com/static/6768e0f32ebd030541dde989/t/687c51f3d1ea102c30431b32/1752977907351/01012741%281%29.jpg?format=1500w' WHERE slug = 'flying-monk-leather';
UPDATE businesses SET photo_url = 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/render/image/public/base44-prod/public/692ddee601cd323333b6e681/6a4fd313b_Screenshot2026-01-04at073332.png?width=1200&amp;height=630&amp;resize=contain' WHERE slug = 'she-must-be-loved';